<a href="https://colab.research.google.com/github/Iman6243/10-steps-to-become-a-data-scientist/blob/master/Opensim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Install Conda**

In [ ]:
!pip install -q condacolab
import condacolab
condacolab.install()

⏬ Downloading https://github.com/conda-forge/miniforge/releases/download/23.11.0-0/Mambaforge-23.11.0-0-Linux-x86_64.sh...
📦 Installing...
📌 Adjusting configuration...
🩹 Patching environment...
⏲ Done in 0:00:14
🔁 Restarting kernel...


**Create a Conda Environment**

In [ ]:
!conda create -n OpenCap python=3.8

Channels:
 - conda-forge
Platform: linux-64
Solving environment: - \ | done


==> WARNING: A newer version of conda exists. <==
    current version: 23.11.0
    latest version: 24.11.0

Please update conda by running

    $ conda update -n base -c conda-forge conda



## Package Plan ##

  environment location: /usr/local/envs/OpenCap

  added / updated specs:
    - python=3.8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bzip2-1.0.8                |       h4bc722e_7         247 KB  conda-forge
    ca-certificates-2024.8.30  |       hbcca054_0         155 KB  conda-forge
    ld_impl_linux-64-2.43      |       h712a8e2_2         654 KB  conda-forge
    libgcc-14.2.0              |       h77fa898_1         829 KB  conda-forge
    libgcc-ng-14.2.0           |       h69a702a_1          53 KB  conda-forge
    libgomp-14.2.0             |       h77fa898_1         450 KB  conda-forge


**Activate the Environment**

In [ ]:
!conda activate OpenCap


CondaError: Run 'conda init' before 'conda activate'



**Install Additional Packages**

In [ ]:
!conda install opensim-org::opensim tensorflow
#!conda install -n OpenCap numpy pandas matplotlib opensim-org::opensim tensorflow
#!conda install opensim-org/label/opensim-org::opensim
# https://github.com/AlessandroCorradini/University-of-California-San-Diego-Big-Data-Specialization
#https://www.kaggle.com/datasets/sanketgandhi29/white-ball-cricket-dataset-teamwise/data

Channels:
 - conda-forge
 - opensim-org
Platform: linux-64
Solving environment: / - \ | / done


==> WARNING: A newer version of conda exists. <==
    current version: 23.11.0
    latest version: 24.11.0

Please update conda by running

    $ conda update -n base -c conda-forge conda



## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - opensim-org::opensim
    - tensorflow


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    absl-py-2.1.0              |     pyhd8ed1ab_1         105 KB  conda-forge
    astunparse-1.6.3           |     pyhd8ed1ab_2          18 KB  conda-forge
    c-ares-1.34.3              |       hb9d3cd8_1         200 KB  conda-forge
    cached-property-1.5.2      |       hd8ed1ab_1           4 KB  conda-forge
    cached_property-1.5.2      |     pyha770c72_1          11 KB  conda-forge
    certifi-2024.8.30          |     pyhd

**Using the Environment**

In [ ]:
!conda run -n OpenCap python your_script.py

## **File Operations**

In [ ]:
#Upload files
import os
from google.colab import files
import shutil

In [ ]:
# Step 1: Create a subfolder
subfolder_name = "AL"
os.makedirs(subfolder_name, exist_ok=True)  # Creates the subfolder if it doesn't exist

# Step 2: Upload the file
uploaded = files.upload()

# Step 3: Move the uploaded file to the subfolder
for filename in uploaded.keys():
    # Move the file to the subfolder
    shutil.move(filename, os.path.join(subfolder_name, filename))

print(f"Files have been saved to '{subfolder_name}' subfolder.")

Saving football_mini.csv to football_mini.csv
Files have been saved to 'AL' subfolder.


In [ ]:
#List files in the current directory
files = os.listdir(subfolder_name)
print("Files in current directory:",files)

Files in current directory: ['sports.csv', 'football_mini.csv', '.ipynb_checkpoints']


## **Machine Learning My_script**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib as plt
from pathlib import Path

**Download Data**

In [ ]:
url="https://raw.githubusercontent.com/amrrs/sample_revenue_dashboard_shiny/refs/heads/master/recommendation.csv"
#Downlaod BigData
url_0="https://raw.githubusercontent.com/amrrs/sample_revenue_dashboard_shiny/refs/heads/master/recommendation.csv?raw=true"
!wget https://raw.githubusercontent.com/amrrs/sample_revenue_dashboard_shiny/refs/heads/master/recommendation.csv
urls=[url,url_0]
#Load Local Data
local=files
#[str(loc8[i]) for i in range(len(loc8))]


--2024-12-09 14:22:51--  https://raw.githubusercontent.com/amrrs/sample_revenue_dashboard_shiny/refs/heads/master/recommendation.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 262 [text/plain]
Saving to: ‘recommendation.csv’

recommendation.csv  100%[===================>]     262  --.-KB/s    in 0s      

2024-12-09 14:22:51 (5.35 MB/s) - ‘recommendation.csv’ saved [262/262]



**Maintaining Data**

In [ ]:
# Get the current working directory
current_directory = Path.cwd()

# Construct a file path
file_path = Path(current_directory / subfolder_name/ local[1])
if file_path.exists():
    print(f"{file_path} exists.")
else:
    print(f"{file_path} does not exist.")

/content/AL/football_mini.csv exists.


In [ ]:
#Read Data Locally
df=pd.read_csv(file_path)

In [ ]:
#Read Data from Web
df=pd.read_csv(urls[0])

In [ ]:
#Maintain Data
df.shape
df.head(5)
df.tail(5)
df.describe()

Unnamed: 0         Age         Value           Wage    Crossing  \
count  100.000000  100.000000  1.000000e+02     100.000000  100.000000   
mean    49.500000   27.950000  5.158500e+07  195960.000000   65.350000   
std     29.011492    3.273323  1.962104e+07   94888.762094   23.101609   
min      0.000000   19.000000  4.000000e+06   21000.000000   11.000000   
25%     24.750000   26.000000  3.750000e+07  125000.000000   57.750000   
50%     49.500000   28.000000  4.825000e+07  182500.000000   74.000000   
75%     74.250000   30.250000  6.212500e+07  240000.000000   82.000000   
max     99.000000   40.000000  1.185000e+08  565000.000000   93.000000   

        Finishing  HeadingAccuracy  ShortPassing     Volleys   Dribbling  ...  \
count  100.000000       100.000000     100.00000  100.000000  100.000000  ...   
mean    64.780000        63.980000      77.23000   63.840000   72.970000  ...   
std     25.636771        22.595691      15.25067   24.016711   23.017541  ...   
min     10.000000        10.000000      29.00000   11.000000   10.000000  ...   
25%     51.750000        54.000000      77.00000   52.750000   67.500000  ...   
50%     74.000000        73.000000      82.00000   73.000000   81.500000  ...   
75%     84.000000        82.000000      85.25000   81.250000   88.000000  ...   
max     95.000000        92.000000      93.00000   90.000000   97.000000  ...   

        Penalties   Composure     Marking  StandingTackle  SlidingTackle  \
count  100.000000  100.000000  100.000000      100.000000     100.000000   
mean    63.980000   82.380000   57.630000       55.130000      51.230000   
std     18.806285    6.675418   24.567637       27.602392      27.635746   
min     11.000000   65.000000   13.000000       10.000000       8.000000   
25%     57.500000   80.000000   34.000000       31.000000      25.000000   
50%     69.000000   83.000000   59.000000       54.500000      47.500000   
75%     78.000000   86.000000   80.250000       84.250000      80.000000   
max     90.000000   96.000000   93.000000       93.000000      91.000000   

         GKDiving  GKHandling   GKKicking  GKPositioning  GKReflexes  
count  100.000000  100.000000  100.000000     100.000000   100.00000  
mean    19.280000   18.960000   18.510000      19.230000    19.38000  
std     25.424509   24.765535   23.029404      25.061482    26.06045  
min      2.000000    2.000000    2.000000       2.000000     3.00000  
25%      7.000000    8.000000    7.000000       7.000000     7.75000  
50%     11.000000   11.000000   11.500000      11.000000    10.00000  
75%     14.250000   14.000000   14.250000      14.250000    14.00000  
max     90.000000   92.000000   91.000000      90.000000    94.00000  

[8 rows x 38 columns]

## **OpenSim**

In [ ]:
import opensim as osim
# Plot GRF
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'opensim'

In [ ]:
# Load model
Path=""
model = osim.Model("path_to_your_model.osim")

NameError: name 'osim' is not defined

In [ ]:
# Set up and run simulation
manager = osim.Manager(model)
state = model.initializeState()
manager.setInitialTime(0)
manager.setFinalTime(1)  # Set your desired time
manager.integrate(state)

In [ ]:
# Calculate GRF
grf_analysis = osim.GroundReactionForce()
grf_analysis.setModel(model)
grf_analysis.calculate(state)

In [ ]:
# Assuming grf_data is the output from the analysis
plt.plot(grf_data.time, grf_data.vertical, label='Vertical GRF')
plt.plot(grf_data.time, grf_data.anterior_posterior, label='AP GRF')
plt.plot(grf_data.time, grf_data.medial_lateral, label='ML GRF')
plt.title('Ground Reaction Forces')
plt.xlabel('Time (s)')
plt.ylabel('Force (N)')
plt.legend()
plt.show()

## **OpenCap**

In [ ]:
import opensim as osim
import matplotlib.pyplot as plt

## **SVM**

In [ ]:
# Step 1: Install required libraries (if not already installed)
#!pip install scikit-learn
#!pip install casadi
#!pip install opensim
#!conda install -c conda-forge opensim

In [ ]:
# Step 2: Import libraries
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

# Step 3: Load the dataset
iris = datasets.load_iris()
#X = pd.DataFrame(iris.data, columns=iris.feature_names)
#y = iris.target
iris.data.shape
X = iris.data  # Features X.shape
y = iris.target  # Target labels y.shape

# Step 4: Preprocess the data
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Step 5: Create SVM model
svm_model = SVC(kernel='linear')  # You can choose different kernels like 'rbf', 'poly', etc.

# Step 6: Train the model
svm_model.fit(X_train, y_train)

# Step 7: Make predictions
y_pred = svm_model.predict(X_test)

# Step 8: Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30



In [ ]:
!python --version


Python 3.10.13


## **Feature selection by lasso regression**

Import Necessary Libraries

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

Load and Prepare Data

In [ ]:
#Load dataset
#data = pd.read_csv('your_dataset.csv')
iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
X.head(5)
y = iris.target
Y=pd.DataFrame(iris.data,columns=iris.target)
# Separate features and target variable
X = data.drop('target', axis=1)
y = data['target']

Split the Data & Fit the Lasso Model

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
lasso = Lasso(alpha=0.1)  # Adjust alpha as needed
lasso.fit(X_train, y_train)

Identify Selected Features

In [ ]:
# Get the coefficients
coefficients = lasso.coef_

# Identify selected features
selected_features = X.columns[coefficients != 0]
print("Selected Features:", selected_features)

Evaluate the Model

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

y_pred = lasso.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R-squared:", r2)